server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: searchframe
      port: 27017
      host: localhost